# Generated by Django 3.1.3 on 2020-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='category',
            field=models.CharField(choices=[('L', 'Login'), ('R', 'Register')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
