# Generated by Django 3.1.3 on 2020-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_logs_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='agent',
            new_name='device',
        ),
        migrations.AddField(
            model_name='logs',
            name='browser',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='device_family',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
