# Generated by Django 3.1.3 on 2020-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20201106_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='os',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
