# Generated by Django 3.1.3 on 2020-11-06 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_logs_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
