# Generated by Django 3.1.3 on 2020-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_falselogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falselogin',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
