# Generated by Django 3.1.7 on 2021-05-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_course_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='sem',
            field=models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='registration',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
